at: AT.c
	gcc AT.c -o $@ -pthread
interviewer1: Interviewer1.c
	gcc Interviewer1.c -o $@
interviewer2: Interviewer2.c
	gcc Interviewer2.c -o $@
interviewer3: Interviewer3.c
	gcc Interviewer3.c -o $@
client: client.c 
	gcc client.c -o $@